
name: Update Timeseries

on:
  schedule:
    - cron: "0 0-23/24 * * *"

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.9"
          architecture: "x64"
      - run: |
          pip install -r requirements_github.txt
          python update_data.py
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Automated update of timeseries"
          git push origin main
